# Generated by Django 5.2.6 on 2025-10-23 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kellcare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for address', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for address', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Latitude coordinate for address', max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, help_text='Longitude coordinate for address', max_digits=9, null=True),
        ),
    ]
